version: '3'
services:
  db:
    container_name: github-api-poc-db
    image: postgres:latest
    restart: always
    ports:
      - 5001:5432
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
